name: Terraform Deploy
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    container:
      image: fredsilvas/alpine-terraform-aws-openvpn:1.0.0
    steps:
      - uses: actions/checkout@v2
      # - name: Create Cache Terraform Dir
      #   run: mkdir -p $TF_PLUGIN_CACHE_DIR
      # - name: Cache Terraform
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ env.TF_PLUGIN_CACHE_DIR }}
      #     key: ${{ runner.os }}-terraform-plugin-cache
      #     restore-keys: ${{ runner.os }}-terraform-plugin-cache

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      - name: Run Terraform Init
        id: init
        run: terraform init
        continue-on-error: false

      - name: Run Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: false

      - name: Run Terraform Plan
        id: plan
        run: terraform plan -out tf.plan
        continue-on-error: false

      - name: Run Terraform Apply
        id: apply
        run: terraform apply tf.plan
        continue-on-error: false